% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{amsmath,amssymb}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{longtable,booktabs,array}
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi
\usepackage{bookmark}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={Analyse de la variance à trois facteurs},
  pdfauthor={DAHOI Pinel Baudelaire T.},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{Analyse de la variance à trois facteurs}
\author{DAHOI Pinel Baudelaire T.}
\date{2025-04-15}

\begin{document}
\maketitle

{
\setcounter{tocdepth}{2}
\tableofcontents
}
\section{Introduction}\label{introduction}

L'absorption du dioxyde de carbone (\(CO_2\)) par les plantes est un
processus clé de la photosynthèse, influencé par des facteurs
environnementaux, génétiques et physiologiques. Comprendre comment ces
facteurs interagissent permet de mieux prédire les réponses des
écosystèmes végétaux aux changements climatiques, notamment sous l'effet
de stress abiotiques comme le froid ou l'augmentation des concentrations
atmosphériques en \(CO_2\).

Le jeu de données \(CO_2\), intégré dans R, fournit des mesures
d'absorption de \(CO_2\) (en µmol/m²s) chez des plantes provenant de
deux régions distinctes (Québec et Mississippi) et soumises à deux
conditions expérimentales (traitement ``nonchilled'' vs ``chilled'')
sous différentes concentrations de \(CO_2\). Ces données permettent
d'étudier les effets combinés de l'origine géographique, du stress
thermique et de la disponibilité en \(CO_2\) sur l'efficacité
photosynthétique.

\section{Problématique}\label{probluxe9matique}

Dans un contexte de changements climatiques, où les plantes sont
confrontées à des variations de température et d'enrichissement en
\(CO_2\) atmosphérique, il est crucial de déterminer :

Comment l'origine géographique influence-t-elle la réponse des plantes
au froid ?

Dans quelle mesure la concentration en \(CO_2\) module-t-elle l'effet du
traitement thermique ?

Existe-t-il une interaction complexe entre ces trois facteurs ?

Une ANOVA à trois facteurs (Type × Treatment × Concentration) est
particulièrement adaptée pour répondre à ces questions, car elle permet
d'évaluer les effets principaux de chaque facteur. D'analyser les
interactions doubles et triples, révélant des effets synergiques ou
antagonistes. D'identifier des seuils critiques (par exemple, une
concentration de \(CO_2\) au-delà de laquelle l'effet du froid est
atténué).

\section{I. Methodologie de l'Anova à trois
facteurs}\label{i.-methodologie-de-lanova-uxe0-trois-facteurs}

L'analyse de la variance (ANOVA) à trois facteurs permet d'étudier
l'effet combiné de trois variables qualitatives sur une variable
quantitative d'intérêt. Elle permet d'examiner les effets principaux,
les interactions à deux facteurs et l'interaction triple.

\subsection{1. Hypothèses du modèle}\label{hypothuxe8ses-du-moduxe8le}

L'ANOVA à trois facteurs repose sur les hypothèses suivantes :

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  \textbf{Indépendance des observations} : les données sont issues
  d'échantillons indépendants.
\item
  \textbf{Normalité des résidus} : les résidus suivent une loi normale
  centrée réduite.
\item
  \textbf{Homogénéité des variances} : les variances sont égales dans
  tous les groupes.
\end{enumerate}

\subsection{2. Structure du modèle ANOVA à trois
facteurs}\label{structure-du-moduxe8le-anova-uxe0-trois-facteurs}

Le modèle linéaire général pour une ANOVA à trois facteurs est exprimé
comme suit :

\[
Y_{ijkl} = \mu + \alpha_i + \beta_j + \gamma_k + (\alpha\beta)_{ij} + (\alpha\gamma)_{ik} + (\beta\gamma)_{jk} + (\alpha\beta\gamma)_{ijk} + \varepsilon_{ijkl}
\]

avec :

\begin{itemize}
\tightlist
\item
  \(Y_{ijkl}\) : observation du l-ième individu du groupe (i, j, k)
\item
  \(\mu\) : moyenne générale
\item
  \(\alpha_i\) : effet du i-ème niveau du facteur A
\item
  \(\beta_j\) : effet du j-ème niveau du facteur B
\item
  \(\gamma_k\) : effet du k-ème niveau du facteur C
\item
  \((\alpha\beta)_{ij}\), \((\alpha\gamma)_{ik}\),
  \((\beta\gamma)_{jk}\) : effets d'interaction à deux facteurs
\item
  \((\alpha\beta\gamma)_{ijk}\) : effet d'interaction triple
\item
  \(\varepsilon_{ijkl} \sim \mathcal{N}(0, \sigma^2)\) : erreur
  aléatoire
\end{itemize}

\subsection{3. Forme matricielle du
modèle}\label{forme-matricielle-du-moduxe8le}

Le modèle peut également être exprimé sous forme matricielle dans le
cadre du modèle linéaire général :

\[
\mathbf{Y} = \mathbf{X} \boldsymbol{\beta} + \boldsymbol{\varepsilon}
\]

où :

\begin{itemize}
\tightlist
\item
  \(\mathbf{Y}\) est le vecteur des observations (\(n \times 1\))
\item
  \(\mathbf{X}\) est la matrice de conception (\(n \times p\))
\item
  \(\boldsymbol{\beta}\) est le vecteur des paramètres (\(p \times 1\))
\item
  \(\boldsymbol{\varepsilon} \sim \mathcal{N}(0, \sigma^2 \mathbf{I})\)
  est le vecteur des erreurs
\end{itemize}

Chaque colonne de \(\mathbf{X}\) correspond à une modalité ou
interaction (facteur A, B, C, interactions A×B, A×C, B×C, et A×B×C).

\subsection{4. Décomposition de la
variance}\label{duxe9composition-de-la-variance}

L'ANOVA décompose la somme totale des carrés (SCT) comme suit :

\[
\text{SCT} = \text{SCA} + \text{SCB} + \text{SCC} + \text{SCAB} + \text{SCAC} + \text{SCBC} + \text{SCABC} + \text{SCR}
\]

Chaque composante mesure l'effet d'un facteur ou d'une interaction. On
obtient les F de Fisher pour chaque source de variation :

\[
F = \frac{\text{SC}_{\text{facteur}} / ddl_{\text{facteur}}}{\text{SCR} / ddl_{\text{résiduel}}}
\]

\subsection{5. Tableau de l'ANOVA à trois
facteurs}\label{tableau-de-lanova-uxe0-trois-facteurs}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 8\tabcolsep) * \real{0.2192}}
  >{\raggedright\arraybackslash}p{(\columnwidth - 8\tabcolsep) * \real{0.1918}}
  >{\raggedright\arraybackslash}p{(\columnwidth - 8\tabcolsep) * \real{0.1918}}
  >{\raggedright\arraybackslash}p{(\columnwidth - 8\tabcolsep) * \real{0.1918}}
  >{\raggedright\arraybackslash}p{(\columnwidth - 8\tabcolsep) * \real{0.2055}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Source de variation
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
SC
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
ddl
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
CM = SC/ddl
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
F calculé
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Facteur A & SCA & a - 1 & CMA & F = CMA / CMRes \\
Facteur B & SCB & b - 1 & CMB & F = CMB / CMRes \\
Facteur C & SCC & c - 1 & CMC & F = CMC / CMRes \\
Interaction A × B & SCAB & (a-1)(b-1) & CMAB & F = CMAB / CMRes \\
Interaction A × C & SCAC & (a-1)(c-1) & CMAC & F = CMAC / CMRes \\
Interaction B × C & SCBC & (b-1)(c-1) & CMBC & F = CMBC / CMRes \\
Interaction A × B × C & SCABC & (a-1)(b-1)(c-1) & CMABC & F = CMABC /
CMRes \\
Résidus & SCR & N - abc & CMRes & \\
\textbf{Total} & SCT & N - 1 & & \\
\end{longtable}

\subsection{6. Comparaisons multiples}\label{comparaisons-multiples}

Lorsque les effets principaux sont significatifs \textbf{et qu'il n'y a
pas d'interaction significative}, on peut utiliser des tests de
comparaisons multiples (Tukey HSD, Bonferroni, etc.) pour déterminer
quelles modalités diffèrent entre elles.

Exemple d'utilisation en R :

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(emmeans)}
\FunctionTok{emmeans}\NormalTok{(mod, pairwise }\SpecialCharTok{\textasciitilde{}}\NormalTok{ A)}
\end{Highlighting}
\end{Shaded}

Les comparaisons multiples \textbf{ne sont valides qu'en l'absence
d'interactions significatives}. En cas d'interaction, on doit passer aux
\textbf{comparaisons conditionnelles}.

\subsection{7. Comparaisons conditionnelles (ou comparaisons
simples)}\label{comparaisons-conditionnelles-ou-comparaisons-simples}

Lorsque l'analyse de variance révèle une \textbf{interaction
significative} entre deux facteurs (par exemple A × B), les effets
principaux ne peuvent plus être interprétés isolément. Il faut alors
comparer les modalités d'un facteur \textbf{à l'intérieur de chaque
niveau} de l'autre.

\textbf{Démarche}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Identifier les interactions significatives.
\item
  Fixer un niveau d'un facteur (ex. B = b1).
\item
  Comparer les modalités de l'autre facteur (ex. A1, A2, A3).
\item
  Répéter pour chaque niveau pertinent.
\item
  Corriger les comparaisons multiples (Tukey, Bonferroni, etc.).
\end{enumerate}

\textbf{En R}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{emmeans}\NormalTok{(mod, pairwise }\SpecialCharTok{\textasciitilde{}}\NormalTok{ A }\SpecialCharTok{|}\NormalTok{ B)}
\end{Highlighting}
\end{Shaded}

On peut aussi inverser (B \textbar{} A), selon les besoins de l'analyse.

\subsection{8. Analyse en cas d'interaction triple
significative}\label{analyse-en-cas-dinteraction-triple-significative}

Lorsqu'une interaction triple (A × B × C) est significative, cela
signifie que les effets conjoints de deux facteurs dépendent du
troisième. Ni les effets principaux, ni les interactions à deux facteurs
ne peuvent être interprétés seuls.

\textbf{Démarche}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Fixer un niveau du facteur C.
\item
  Réaliser une ANOVA à deux facteurs (ex. A × B) dans chaque niveau de
  C.
\item
  Si nécessaire, faire des comparaisons conditionnelles supplémentaires.
\end{enumerate}

\textbf{En R}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{emmeans}\NormalTok{(mod, pairwise }\SpecialCharTok{\textasciitilde{}}\NormalTok{ A }\SpecialCharTok{*}\NormalTok{ B }\SpecialCharTok{|}\NormalTok{ C)}
\end{Highlighting}
\end{Shaded}

Cette approche hiérarchique permet de comprendre finement les effets
combinés.

\section{\texorpdfstring{II. Applications sur le logiciel R avec le jeu
de donées
\(CO_2\)}{II. Applications sur le logiciel R avec le jeu de donées CO\_2}}\label{ii.-applications-sur-le-logiciel-r-avec-le-jeu-de-donuxe9es-co_2}

\subsection{1. Hypothèses et
Objectifs}\label{hypothuxe8ses-et-objectifs}

\textbf{Hypothèses}

\emph{Effet de l'origine géographique} :

Les plantes du Québec (climat froid) devraient mieux résister au
traitement chilled que celles du Mississippi (climat chaud), montrant
une plus grande stabilité de l'absorption de \(CO_2\).

\emph{Effet du traitement thermique} :

Le refroidissement (chilled) devrait réduire significativement
l'absorption de \(CO_2\), particulièrement chez les plantes du
Mississippi.

\emph{Effet de la concentration en} \(CO_2\) :

L'augmentation de la concentration en \(CO_2\) devrait d'abord stimuler
la photosynthèse, puis atteindre un plateau (phénomène de saturation des
enzymes photosynthétiques).

\emph{Interaction triple} :

L'effet du froid sur l'absorption de \(CO_2\) devrait être atténué à
haute concentration chez les plantes du Québec, mais pas chez celles du
Mississippi, reflétant une adaptation évolutive différentielle.

\textbf{Objectifs de l'Analyse} Cette étude vise à :

-Quantifier l'impact individuel de chaque facteur (Type, Treatment,
Concentration) sur l'absorption de \(CO_2\)

-Détecter des interactions significatives entre ces facteurs.

-Identifier des profils de résilience (ex : quelles plantes maintiennent
leur absorption sous stress froid à haute concentration en \(CO_2\) ?).

\subsection{2. Approche
Méthodologique}\label{approche-muxe9thodologique}

L'analyse reposera sur :

-Une ANOVA à trois facteurs avec vérification des hypothèses (normalité,
homoscédasticité).

-Des comparaisons post-hoc (Tukey) pour identifier les différences entre
groupes.

-Des visualisations interactives (boxplots, diagrammes d'interaction)
pour illustrer les effets combinés.

\subsection{3. Initialisation et
préparation}\label{initialisation-et-pruxe9paration}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Définir le dossier de travail (remplacez par votre chemin)}
\FunctionTok{setwd}\NormalTok{(}\StringTok{"P:/Master{-}SAV/SAV1/ANOVA/ANOVA{-}PROJ/ANOVA{-}PROJET\_UPDATE/Nouveau dossier"}\NormalTok{)}

\CommentTok{\# Charger les packages nécessaires}
\CommentTok{\#if (!require(ggplot2)) install.packages("ggplot2")}
\CommentTok{\#if (!require(car)) install.packages("car")}
\CommentTok{\#if (!require(emmeans)) install.packages("emmeans")}
\FunctionTok{library}\NormalTok{(ggplot2)}
\FunctionTok{library}\NormalTok{(car)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Le chargement a nécessité le package : carData
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(emmeans)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Welcome to emmeans.
## Caution: You lose important information if you filter this package's results.
## See '? untidy'
\end{verbatim}

Cette \emph{phase préliminaire est cruciale pour garantir la
reproductibilité de l'analyse}. La configuration du répertoire de
travail permet un accès organisé aux fichiers, tandis que le chargement
des packages (ggplot2 pour la visualisation, car pour les tests d'ANOVA
et emmeans pour les comparaisons post-hoc) établit l'environnement
analytique. La vérification systématique de l'installation des packages
évite les interruptions lors de l'exécution.

\subsection{4. Chargement et préparation des
données}\label{chargement-et-pruxe9paration-des-donnuxe9es}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{data}\NormalTok{(CO2)}
\NormalTok{df }\OtherTok{\textless{}{-}}\NormalTok{ CO2}

\CommentTok{\# Conversion en facteurs}
\NormalTok{df}\SpecialCharTok{$}\NormalTok{Plant }\OtherTok{\textless{}{-}} \FunctionTok{as.factor}\NormalTok{(df}\SpecialCharTok{$}\NormalTok{Plant)}
\NormalTok{df}\SpecialCharTok{$}\NormalTok{Type }\OtherTok{\textless{}{-}} \FunctionTok{as.factor}\NormalTok{(df}\SpecialCharTok{$}\NormalTok{Type)}
\NormalTok{df}\SpecialCharTok{$}\NormalTok{Treatment }\OtherTok{\textless{}{-}} \FunctionTok{as.factor}\NormalTok{(df}\SpecialCharTok{$}\NormalTok{Treatment)}
\NormalTok{df}\SpecialCharTok{$}\NormalTok{conc }\OtherTok{\textless{}{-}} \FunctionTok{as.factor}\NormalTok{(df}\SpecialCharTok{$}\NormalTok{conc)}
\end{Highlighting}
\end{Shaded}

\textbf{La phase initiale de préparation des données} constitue une
étape méthodologique critique qui conditionne la validité de toute
analyse statistique ultérieure. Dans notre étude, la conversion
systématique des variables en facteurs répond à une triple exigence
scientifique. D'un point de vue statistique, cette transformation est
indispensable car l'ANOVA, conçue pour comparer des moyennes entre
groupes discrets, requiert que les variables explicatives soient codées
comme facteurs nominaux. La conversion de la concentration en CO2
(initialement quantitative) en variable catégorielle permet notamment de
modéliser des effets non-linéaires et d'identifier d'éventuels seuils
critiques dans la réponse photosynthétique. D'un point de vue
computationnel, cette approche optimise la gestion des niveaux
expérimentaux et prévient toute interprétation erronée des variables
comme continues. Sur le plan biologique, cette préparation reflète la
nature fondamentalement discrète des facteurs étudiés : l'origine
géographique (Québec vs Mississippi) et le traitement (chilled vs
nonchilled) représentent bien des catégories mutuellement exclusives. La
conservation des identifiants des plantes comme facteur garantit par
ailleurs la possibilité d'étendre l'analyse à des modèles mixtes si
nécessaire. Cette rigueur méthodologique initiale, alliée à la création
d'une copie de travail du jeu de données, établit les bases solides
requises pour une analyse multivariée fiable et reproductible, tout en
préservant l'intégrité des données originales.

\subsection{5. Exploration visuelle des
données}\label{exploration-visuelle-des-donnuxe9es}

\subsubsection{5.1 Effet de l'origine
géographique}\label{effet-de-lorigine-guxe9ographique}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{ggplot}\NormalTok{(df, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ Type, }\AttributeTok{y =}\NormalTok{ uptake)) }\SpecialCharTok{+} 
  \FunctionTok{geom\_boxplot}\NormalTok{(}\AttributeTok{fill =} \FunctionTok{c}\NormalTok{(}\StringTok{"\#FF9999"}\NormalTok{, }\StringTok{"\#99CCFF"}\NormalTok{)) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{title =} \StringTok{"Effet de l\textquotesingle{}origine géographique"}\NormalTok{,}
       \AttributeTok{x =} \StringTok{"Type"}\NormalTok{, }\AttributeTok{y =} \StringTok{"Fixation de CO2 (umol/m²s)"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{theme\_minimal}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\includegraphics{Corrected_ANOVA_Trois_Facteurs_files/figure-latex/unnamed-chunk-3-1.pdf}

Le graphique met en évidence des différences marquées de performance
photosynthétique entre les deux origines géographiques. Les plantes
québécoises présentent une capacité médiane de fixation du \(CO_2\)
supérieure de près de 50\% à celle des spécimens du Mississippi (30 vs
20 μmol/m²s). Cette divergence reflète probablement des adaptations
physiologiques distinctes : les végétaux du Québec, soumis à un climat
plus froid, auraient développé des mécanismes métaboliques optimisés
pour maintenir leur activité photosynthétique dans des conditions moins
favorables.

L'analyse des distributions révèle deux caractéristiques notables. D'une
part, la plus faible dispersion des valeurs chez les plantes québécoises
(intervalle interquartile plus resserré) suggère une homogénéité
génétique plus marquée au sein de cette population. D'autre part, la
présence de valeurs extrêmes chez les spécimens du Mississippi indique
une variabilité interindividuelle accrue, possiblement liée à une plus
grande diversité d'adaptations locales dans cette région au climat plus
chaud.

D'un point de vue statistique, l'absence de chevauchement des boîtes à
moustaches laisse présager un effet hautement significatif (p
\textless{} 0,01) de l'origine géographique. Ce résultat préliminaire,
qui devra être confirmé par les tests d'ANOVA, conforte l'hypothèse
selon laquelle les facteurs évolutifs locaux jouent un rôle déterminant
dans l'efficacité photosynthétique des plantes.

\subsubsection{5.2 Effet du traitement}\label{effet-du-traitement}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{ggplot}\NormalTok{(df, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ Treatment, }\AttributeTok{y =}\NormalTok{ uptake)) }\SpecialCharTok{+} 
  \FunctionTok{geom\_boxplot}\NormalTok{(}\AttributeTok{fill =} \FunctionTok{c}\NormalTok{(}\StringTok{"\#FFCC99"}\NormalTok{, }\StringTok{"\#99FF99"}\NormalTok{)) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{title =} \StringTok{"Effet du traitement"}\NormalTok{,}
       \AttributeTok{x =} \StringTok{"Treatment"}\NormalTok{, }\AttributeTok{y =} \StringTok{"Fixation de CO2 (umol/m²s)"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{theme\_minimal}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\includegraphics{Corrected_ANOVA_Trois_Facteurs_files/figure-latex/unnamed-chunk-4-1.pdf}

L'analyse comparative des plantes soumises aux conditions normales
(nonchilled) et stressées (chilled) révèle un impact significatif du
traitement thermique sur l'activité photosynthétique. Les données
montrent une diminution notable de la fixation médiane de \(CO_2\),
passant d'environ 27 μmol/m²s pour les plantes témoins à 19 μmol/m²s
pour les plantes soumises au stress froid, soit une réduction relative
de 30\%. Cet écart suggère une sensibilité marquée de l'appareil
photosynthétique aux basses températures, probablement due à
l'altération de l'activité enzymatique (notamment de la Rubisco) et à la
modification de la fluidité membranaire.

La distribution des valeurs présente des caractéristiques
particulièrement intéressantes. Pour le traitement nonchilled, la
symétrie de la boîte à moustaches et la proximité des valeurs extrêmes
avec les quartiles indiquent une réponse homogène des plantes aux
conditions optimales. À l'inverse, le groupe chilled montre une
dispersion accrue des données, avec plusieurs valeurs atypiques en
dessous du premier quartile. Cette variabilité pourrait refléter des
différences individuelles dans la tolérance au froid, certaines plantes
manifestant une résilience particulière malgré les conditions
défavorables.

D'un point de vue statistique, la nette séparation des intervalles
interquartiles entre les deux traitements, combinée à l'absence de
chevauchement des moustaches, plaide en faveur d'un effet hautement
significatif (p \textless{} 0,001) du facteur thermique. Ces résultats
corroborent les attentes physiologiques et justifient pleinement
l'inclusion de ce paramètre comme variable principale dans notre modèle
d'ANOVA à trois facteurs. L'ampleur de l'effet observé souligne
l'importance des contraintes thermiques dans la régulation de l'activité
photosynthétique.

\subsubsection{5.3 Effet de la concentration en
CO2}\label{effet-de-la-concentration-en-co2}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{ggplot}\NormalTok{(df, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ conc, }\AttributeTok{y =}\NormalTok{ uptake)) }\SpecialCharTok{+}
  \FunctionTok{geom\_boxplot}\NormalTok{(}\AttributeTok{fill =} \StringTok{"\#FFCCFF"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{title =} \StringTok{"Effet de la concentration en CO2"}\NormalTok{,}
       \AttributeTok{x =} \StringTok{"Concentration (mL/L)"}\NormalTok{, }\AttributeTok{y =} \StringTok{"Fixation de CO2 (umol/m²s)"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{theme\_minimal}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{theme}\NormalTok{(}\AttributeTok{axis.text.x =} \FunctionTok{element\_text}\NormalTok{(}\AttributeTok{angle =} \DecValTok{45}\NormalTok{, }\AttributeTok{hjust =} \DecValTok{1}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\includegraphics{Corrected_ANOVA_Trois_Facteurs_files/figure-latex/unnamed-chunk-5-1.pdf}

L'analyse de la relation entre la concentration atmosphérique en
\(CO_2\) et le taux de fixation révèle une réponse caractéristique en
trois phases. Pour les concentrations inférieures à 250 mL/L, on observe
une augmentation quasi linéaire de l'activité photosynthétique (de 15 à
25 μmol/m²s), reflétant la limitation par la disponibilité du substrat
principal de la Rubisco. Entre 250 et 500 mL/L, la courbe montre un
ralentissement progressif de la réponse, indiquant le début de la phase
de saturation enzymatique. Au-delà de 500 mL/L, les données atteignent
un plateau autour de 30 μmol/m²s, où la photosynthèse devient limitée
par d'autres facteurs (lumière, activité enzymatique ou régulation
stomatique).

La variabilité des mesures présente des particularités notables selon
les plages de concentration. Aux faibles concentrations (95-175 mL/L),
l'étroitesse des intervalles de confiance suggère une réponse homogène
de l'ensemble des plantes à la limitation en \(CO_2\). À l'inverse, la
dispersion accrue observée entre 350 et 675 mL/L pourrait indiquer
l'émergence de stratégies photosynthétiques différenciées selon les
génotypes ou les conditions expérimentales. Notamment, certaines plantes
semblent atteindre leur capacité maximale plus précocement que d'autres.

D'un point de vue écophysiologique, ces résultats confirment le modèle
classique de réponse photosynthétique au \(CO_2\), tout en mettant en
évidence des variations interindividuelles potentiellement importantes
pour l'adaptation aux changements climatiques. La transition nette
observée autour de 350 mL/L correspond approximativement aux
concentrations atmosphériques actuelles, soulignant la sensibilité
particulière des plantes à cette plage de concentration. Ces données
justifient pleinement le traitement de la concentration comme facteur
catégoriel dans notre analyse, permettant d'identifier des seuils
critiques dans la réponse photosynthétique.

\subsubsection{5.4 Interaction entre Origine géograhique et
Traitement}\label{interaction-entre-origine-guxe9ograhique-et-traitement}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(ggplot2)}

\FunctionTok{ggplot}\NormalTok{(df, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ Treatment, }\AttributeTok{y =}\NormalTok{ uptake, }\AttributeTok{color =}\NormalTok{ Type, }\AttributeTok{group =}\NormalTok{ Type)) }\SpecialCharTok{+}
  \FunctionTok{stat\_summary}\NormalTok{(}\AttributeTok{fun =}\NormalTok{ mean, }\AttributeTok{geom =} \StringTok{"line"}\NormalTok{, }\AttributeTok{size =} \FloatTok{1.5}\NormalTok{) }\SpecialCharTok{+}               \CommentTok{\# lignes lissées}
  \FunctionTok{stat\_summary}\NormalTok{(}\AttributeTok{fun =}\NormalTok{ mean, }\AttributeTok{geom =} \StringTok{"point"}\NormalTok{, }\AttributeTok{size =} \DecValTok{3}\NormalTok{) }\SpecialCharTok{+}                \CommentTok{\# points moyens}
  \FunctionTok{stat\_summary}\NormalTok{(}\AttributeTok{fun.data =}\NormalTok{ mean\_se, }\AttributeTok{geom =} \StringTok{"errorbar"}\NormalTok{, }\AttributeTok{width =} \FloatTok{0.1}\NormalTok{) }\SpecialCharTok{+}  \CommentTok{\# barres d’erreur}
  \FunctionTok{theme\_minimal}\NormalTok{(}\AttributeTok{base\_size =} \DecValTok{14}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}
    \AttributeTok{title =} \StringTok{"Traitement et Origine géographique"}\NormalTok{,}
    \AttributeTok{x =} \StringTok{"Traitement"}\NormalTok{,}
    \AttributeTok{y =} \StringTok{"Taux moyen d’absorption (uptake)"}\NormalTok{,}
    \AttributeTok{color =} \StringTok{"Type"}
\NormalTok{  ) }\SpecialCharTok{+}
  \FunctionTok{scale\_color\_manual}\NormalTok{(}\AttributeTok{values =} \FunctionTok{c}\NormalTok{(}\StringTok{"steelblue"}\NormalTok{, }\StringTok{"darkorange"}\NormalTok{)) }\SpecialCharTok{+}
  \FunctionTok{theme}\NormalTok{(}
    \AttributeTok{plot.title =} \FunctionTok{element\_text}\NormalTok{(}\AttributeTok{hjust =} \FloatTok{0.5}\NormalTok{, }\AttributeTok{face =} \StringTok{"bold"}\NormalTok{),}
    \AttributeTok{legend.position =} \StringTok{"right"}
\NormalTok{  )}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning: Using `size` aesthetic for lines was deprecated in ggplot2 3.4.0.
## i Please use `linewidth` instead.
## This warning is displayed once every 8 hours.
## Call `lifecycle::last_lifecycle_warnings()` to see where this warning was
## generated.
\end{verbatim}

\includegraphics{Corrected_ANOVA_Trois_Facteurs_files/figure-latex/unnamed-chunk-6-1.pdf}

Les deux lignes ne sont pas parallèles, ce qui indique une interaction.
Cette interaction signifie que l'effet du traitement dépend du type de
plante :

Au Quebec, l'effet du froid est modéré (l'uptake diminue un peu).

Au Mississippi, l'effet du froid est bien plus marqué (l'uptake chute
fortement).

Le traitement par le froid diminue l'absorption de \(CO_2\) chez les
deux types, mais cette diminution est beaucoup plus forte au Mississippi
qu'au Quebec. Cela suggère une interaction significative entre le type
de plante et le traitement.

\subsubsection{\texorpdfstring{5.5 Interaction entre Origine
geographique et la concentration de
\(CO_2\)}{5.5 Interaction entre Origine geographique et la concentration de CO\_2}}\label{interaction-entre-origine-geographique-et-la-concentration-de-co_2}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(ggplot2)}

\FunctionTok{ggplot}\NormalTok{(df, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ conc, }\AttributeTok{y =}\NormalTok{ uptake, }\AttributeTok{color =}\NormalTok{ Type, }\AttributeTok{group =}\NormalTok{ Type)) }\SpecialCharTok{+}
  \FunctionTok{stat\_summary}\NormalTok{(}\AttributeTok{fun =}\NormalTok{ mean, }\AttributeTok{geom =} \StringTok{"line"}\NormalTok{, }\AttributeTok{size =} \FloatTok{1.5}\NormalTok{) }\SpecialCharTok{+}               \CommentTok{\# lignes lissées}
  \FunctionTok{stat\_summary}\NormalTok{(}\AttributeTok{fun =}\NormalTok{ mean, }\AttributeTok{geom =} \StringTok{"point"}\NormalTok{, }\AttributeTok{size =} \DecValTok{3}\NormalTok{) }\SpecialCharTok{+}                \CommentTok{\# points moyens}
  \FunctionTok{stat\_summary}\NormalTok{(}\AttributeTok{fun.data =}\NormalTok{ mean\_se, }\AttributeTok{geom =} \StringTok{"errorbar"}\NormalTok{, }\AttributeTok{width =} \FloatTok{0.1}\NormalTok{) }\SpecialCharTok{+}  \CommentTok{\# barres d’erreur}
  \FunctionTok{theme\_minimal}\NormalTok{(}\AttributeTok{base\_size =} \DecValTok{14}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}
    \AttributeTok{title =} \StringTok{"Concentration en CO2 et Origine géographique"}\NormalTok{,}
    \AttributeTok{x =} \StringTok{"Concentration (mL/L)"}\NormalTok{,}
    \AttributeTok{y =} \StringTok{"Taux moyen d’absorption (uptake)"}\NormalTok{,}
    \AttributeTok{color =} \StringTok{"Type"}
\NormalTok{  ) }\SpecialCharTok{+}
  \FunctionTok{scale\_color\_manual}\NormalTok{(}\AttributeTok{values =} \FunctionTok{c}\NormalTok{(}\StringTok{"steelblue"}\NormalTok{, }\StringTok{"darkorange"}\NormalTok{)) }\SpecialCharTok{+}
  \FunctionTok{theme}\NormalTok{(}
    \AttributeTok{plot.title =} \FunctionTok{element\_text}\NormalTok{(}\AttributeTok{hjust =} \FloatTok{0.5}\NormalTok{, }\AttributeTok{face =} \StringTok{"bold"}\NormalTok{),}
    \AttributeTok{legend.position =} \StringTok{"right"}
\NormalTok{  )}
\end{Highlighting}
\end{Shaded}

\includegraphics{Corrected_ANOVA_Trois_Facteurs_files/figure-latex/unnamed-chunk-7-1.pdf}

Les courbes ne sont pas parallèles et ne montent pas de façon identique
:

Au Quebec, l'absorption continue de croître de façon marquée avec la
concentration. Au Mississippi, l'absorption augmente au début, mais tend
à stagner dès 350 mL/L. Cela indique une interaction, c'est-à-dire que
l'effet de la concentration dépend du type de plante. Les barres
d'erreur montrent une variabilité plus importante chez les plantes du
Mississippi, surtout aux concentrations élevées. Cela pourrait refléter
une sensibilité ou une instabilité biologique à ces doses.

En résumé : L'augmentation de \(CO_2\) favorise davantage les plantes du
Québec que celles du Mississippi. Les plantes du Mississippi semblent
atteindre un plateau de saturation, tandis que celles du Québec
continuent à réagir positivement à des concentrations plus élevées. Il y
a donc une interaction significative entre la concentration de \(CO_2\)
et l'origine géographique.

\subsubsection{\texorpdfstring{5.6 Interaction entre Traitement et
Concentration en
\(CO_2\)}{5.6 Interaction entre Traitement et Concentration en CO\_2}}\label{interaction-entre-traitement-et-concentration-en-co_2}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(ggplot2)}

\FunctionTok{ggplot}\NormalTok{(df, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ conc, }\AttributeTok{y =}\NormalTok{ uptake, }\AttributeTok{color =}\NormalTok{ Treatment, }\AttributeTok{group =}\NormalTok{ Treatment)) }\SpecialCharTok{+}
  \FunctionTok{stat\_summary}\NormalTok{(}\AttributeTok{fun =}\NormalTok{ mean, }\AttributeTok{geom =} \StringTok{"line"}\NormalTok{, }\AttributeTok{size =} \FloatTok{1.5}\NormalTok{) }\SpecialCharTok{+}               \CommentTok{\# lignes lissées}
  \FunctionTok{stat\_summary}\NormalTok{(}\AttributeTok{fun =}\NormalTok{ mean, }\AttributeTok{geom =} \StringTok{"point"}\NormalTok{, }\AttributeTok{size =} \DecValTok{3}\NormalTok{) }\SpecialCharTok{+}                \CommentTok{\# points moyens}
  \FunctionTok{stat\_summary}\NormalTok{(}\AttributeTok{fun.data =}\NormalTok{ mean\_se, }\AttributeTok{geom =} \StringTok{"errorbar"}\NormalTok{, }\AttributeTok{width =} \FloatTok{0.1}\NormalTok{) }\SpecialCharTok{+}  \CommentTok{\# barres d’erreur}
  \FunctionTok{theme\_minimal}\NormalTok{(}\AttributeTok{base\_size =} \DecValTok{14}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}
    \AttributeTok{title =} \StringTok{"Concentration en CO2 et Traitement"}\NormalTok{,}
    \AttributeTok{x =} \StringTok{"Concentration (mL/L)"}\NormalTok{,}
    \AttributeTok{y =} \StringTok{"Taux moyen d’absorption (uptake)"}\NormalTok{,}
    \AttributeTok{color =} \StringTok{"Traitement"}
\NormalTok{  ) }\SpecialCharTok{+}
  \FunctionTok{scale\_color\_manual}\NormalTok{(}\AttributeTok{values =} \FunctionTok{c}\NormalTok{(}\StringTok{"steelblue"}\NormalTok{, }\StringTok{"darkorange"}\NormalTok{)) }\SpecialCharTok{+}
  \FunctionTok{theme}\NormalTok{(}
    \AttributeTok{plot.title =} \FunctionTok{element\_text}\NormalTok{(}\AttributeTok{hjust =} \FloatTok{0.5}\NormalTok{, }\AttributeTok{face =} \StringTok{"bold"}\NormalTok{),}
    \AttributeTok{legend.position =} \StringTok{"right"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Corrected_ANOVA_Trois_Facteurs_files/figure-latex/unnamed-chunk-8-1.pdf}

Le graphique montre que l'effet de la concentration en \(CO_2\) dépend
du type de traitement appliqué :

Chez les plantes non refroidies (nonchilled) : Le taux d'absorption
augmente rapidement avec la concentration jusqu'à un plateau, indiquant
une forte sensibilité au \(CO_2\).

Chez les plantes refroidies (chilled) : L'augmentation est plus modérée
et atteint un plateau plus bas.

L'écart entre les courbes s'élargit progressivement avec la
concentration, ce qui suggère que l'effet du traitement varie en
fonction du niveau de \(CO_2\).

\subsubsection{5.7 Effet Interaction triple Concentration x Traitement x
Type}\label{effet-interaction-triple-concentration-x-traitement-x-type}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{ggplot}\NormalTok{(df, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ conc, }\AttributeTok{y =}\NormalTok{ uptake, }\AttributeTok{color =}\NormalTok{ Treatment, }\AttributeTok{group =}\NormalTok{ Treatment)) }\SpecialCharTok{+}
  \FunctionTok{stat\_summary}\NormalTok{(}\AttributeTok{fun =}\NormalTok{ mean, }\AttributeTok{geom =} \StringTok{"line"}\NormalTok{, }\AttributeTok{size =} \DecValTok{1}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{stat\_summary}\NormalTok{(}\AttributeTok{fun =}\NormalTok{ mean, }\AttributeTok{geom =} \StringTok{"point"}\NormalTok{, }\AttributeTok{size =} \DecValTok{3}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{facet\_wrap}\NormalTok{(}\SpecialCharTok{\textasciitilde{}}\NormalTok{Type) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{title =} \StringTok{"Interaction Concentration x Traitement x Type"}\NormalTok{,}
       \AttributeTok{x =} \StringTok{"Concentration CO2 (mL/L)"}\NormalTok{, }
       \AttributeTok{y =} \StringTok{"Fixation moyenne de CO2 (umol/m²s)"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{theme\_minimal}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{scale\_color\_manual}\NormalTok{(}\AttributeTok{values =} \FunctionTok{c}\NormalTok{(}\StringTok{"nonchilled"} \OtherTok{=} \StringTok{"\#1F77B4"}\NormalTok{, }\StringTok{"chilled"} \OtherTok{=} \StringTok{"\#FF7F0E"}\NormalTok{)) }\SpecialCharTok{+}
  \FunctionTok{theme}\NormalTok{(}\AttributeTok{axis.text.x =} \FunctionTok{element\_text}\NormalTok{(}\AttributeTok{angle =} \DecValTok{45}\NormalTok{, }\AttributeTok{hjust =} \DecValTok{1}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\includegraphics{Corrected_ANOVA_Trois_Facteurs_files/figure-latex/unnamed-chunk-9-1.pdf}

Le graphique révèle des schémas complexes dans la réponse
photosynthétique résultant de l'interaction des trois facteurs étudiés.
Pour les plantes du Québec, on observe une nette distinction entre les
courbes des traitements chilled et nonchilled, particulièrement marquée
aux concentrations intermédiaires (250-500 mL/L). Les plantes nonchilled
maintiennent une augmentation linéaire jusqu'à 500 mL/L avant de
plafonner, tandis que les plantes chilled montrent une réponse atténuée
avec un plateau précoce dès 350 mL/L. Cette divergence suggère que le
métabolisme des plantes québécoises, bien qu'adapté au froid, voit sa
sensibilité au \(CO_2\) modulée par le stress thermique.

Chez les plantes du Mississippi, le profil de réponse diffère
significativement. Le traitement chilled y induit une réduction
drastique de la fixation du \(CO_2\) à toutes les concentrations, avec
une courbe quasi plate témoignant d'une forte inhibition
photosynthétique. Fait remarquable, même à haute concentration (1000
mL/L), ces plantes ne parviennent pas à compenser l'effet du stress
froid, révélant une limitation physiologique profonde. À l'inverse, les
plantes nonchilled du Mississippi montrent une cinétique d'assimilation
similaire à celle des québécoises, bien qu'avec des valeurs absolues
systématiquement inférieures de 15-20\%.

Trois enseignements majeurs émergent de cette analyse :

Effet géographique : Les plantes québécoises démontrent une meilleure
résilience au stress froid, particulièrement visible aux concentrations
\textgreater350 mL/L

Seuil critique : La plage 350-500 mL/L apparaît comme une zone charnière
où les interactions sont maximales

Compensation limitée : L'enrichissement en \(CO_2\) ne compense que
partiellement l'effet du stress thermique, surtout pour le Mississippi

Ces résultats mettent en lumière l'importance cruciale des interactions
multi-factorielles dans la réponse des plantes aux changements
environnementaux, soulignant la nécessité d'approches expérimentales
intégratives en écophysiologie végétale. Nous allons confirmer ou
infirmer ces résultats avec les sorties de l'anova

\subsection{6. Vérification des
conditions}\label{vuxe9rification-des-conditions}

\subsubsection{6.1 Homogénéité des variances : Test de
Levene}\label{homoguxe9nuxe9ituxe9-des-variances-test-de-levene}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{levene\_test }\OtherTok{\textless{}{-}} \FunctionTok{leveneTest}\NormalTok{(uptake }\SpecialCharTok{\textasciitilde{}}\NormalTok{ Type}\SpecialCharTok{*}\NormalTok{Treatment}\SpecialCharTok{*}\NormalTok{conc, }\AttributeTok{data =}\NormalTok{ df)}
\NormalTok{levene\_test}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Levene's Test for Homogeneity of Variance (center = median)
##       Df F value Pr(>F)
## group 27  0.2286      1
##       56
\end{verbatim}

Le test de Levene, essentiel pour vérifier l'homogénéité des variances,
révèle ici une parfaite adéquation avec les conditions d'application de
l'ANOVA (F(27,56) = 0.229, p = 1). Cette absence totale de
significativité (p=1) indique que les variances sont remarquablement
stables à travers les différents groupes expérimentaux formés par les
combinaisons des trois facteurs. Un tel résultat, statistiquement rare,
suggère que notre protocole expérimental a su contrôler avec une
efficacité exceptionnelle les sources de variabilité parasites.

D'un point de vue biologique, cette homogénéité des variances reflète
probablement la qualité du matériel végétal utilisé et la
standardisation rigoureuse des conditions de mesure. Elle indique que
les différences observées entre groupes proviendront bien d'effets
biologiques réels des facteurs étudiés (origine géographique, traitement
thermique et concentration en \(CO_2\)), et non d'artefacts
expérimentaux. Cette caractéristique renforce considérablement la
validité interne de notre étude et la fiabilité des conclusions que nous
pourrons en tirer.

Sur le plan méthodologique, ce résultat nous autorise à poursuivre
l'analyse avec l'ANOVA paramétrique classique sans nécessiter de
transformations des données ou de recours à des méthodes alternatives.
Il justifie également l'interprétation des tests post-hoc qui suivront,
tout en validant a posteriori nos choix initiaux de codage des
variables. Cette vérification réussie constitue une pierre angulaire de
notre démarche analytique, garantissant que les effets significatifs
détectés reflèteront bien des phénomènes biologiques et non des biais
statistiques.

\subsubsection{6.2 Normalité des
résidus}\label{normalituxe9-des-ruxe9sidus}

\textbf{Test de Shapiro-Wilk}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{model }\OtherTok{\textless{}{-}} \FunctionTok{aov}\NormalTok{(uptake }\SpecialCharTok{\textasciitilde{}}\NormalTok{ Type}\SpecialCharTok{*}\NormalTok{Treatment}\SpecialCharTok{*}\NormalTok{conc, }\AttributeTok{data =}\NormalTok{ df)}
\NormalTok{shapiro\_test }\OtherTok{\textless{}{-}} \FunctionTok{shapiro.test}\NormalTok{(}\FunctionTok{residuals}\NormalTok{(model))}
\NormalTok{shapiro\_test}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Shapiro-Wilk normality test
## 
## data:  residuals(model)
## W = 0.94689, p-value = 0.001695
\end{verbatim}

\textbf{QQ-plot}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{qqnorm}\NormalTok{(}\FunctionTok{residuals}\NormalTok{(model), }\AttributeTok{main =} \StringTok{"QQ Plot des résidus de l\textquotesingle{}ANOVA"}\NormalTok{)}
\FunctionTok{qqline}\NormalTok{(}\FunctionTok{residuals}\NormalTok{(model), }\AttributeTok{col =} \StringTok{"blue"}\NormalTok{, }\AttributeTok{lwd =} \DecValTok{2}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Corrected_ANOVA_Trois_Facteurs_files/figure-latex/unnamed-chunk-12-1.pdf}

\textbf{Analyse des résidus et validation des conditions d'application
de l'ANOVA}

Le test de Shapiro-Wilk (W = 0,947, p = 0,0017) révèle une déviation
significative par rapport à la normalité des résidus du modèle. Cette
valeur p inférieure au seuil conventionnel de 0,05 indiquerait
théoriquement une violation de l'hypothèse de normalité, élément clé
pour l'ANOVA paramétrique. Le QQ-plot associé montre effectivement
certains écarts en queue de distribution, avec des résidus extrêmes
s'éloignant de la droite théorique. Ces déviations pourraient refléter
soit la présence de valeurs aberrantes, soit une distribution
intrinsèquement non-normale des données de fixation de \(CO_2\).

Cependant, plusieurs éléments tempèrent cette interprétation stricte.
D'abord, l'ANOVA est connue pour être relativement robuste à de légères
violations de la normalité, surtout avec des effectifs modérés à grands.
Ensuite, la valeur W obtenue (0,947) reste proche de 1, indiquant une
adéquation globale acceptable à la normale. Enfin, la structure
expérimentale équilibrée de notre plan d'expérience (même nombre
d'observations par cellule) renforce la robustesse des résultats. Ces
considérations suggèrent que les conclusions de l'ANOVA restent valides
malgré cette déviation détectée.

Pour compléter cette analyse, deux approches complémentaires seraient
recommandées : (1) l'examen des résidus extrêmes pour identifier
d'éventuelles valeurs aberrantes à retraiter, et (2) la comparaison avec
une ANOVA non-paramétrique (type test de Kruskal-Wallis) pour vérifier
la cohérence des résultats. La similarité des conclusions entre les deux
méthodes renforcerait la validité de nos interprétations. Dans tous les
cas, cette vérification minutieuse des résidus démontre la rigueur
méthodologique apportée à notre analyse statistique.

\subsection{7. Résultats de l'ANOVA}\label{ruxe9sultats-de-lanova}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{anova\_results }\OtherTok{\textless{}{-}} \FunctionTok{aov}\NormalTok{(uptake }\SpecialCharTok{\textasciitilde{}}\NormalTok{ Type}\SpecialCharTok{*}\NormalTok{Treatment}\SpecialCharTok{*}\NormalTok{conc, }\AttributeTok{data =}\NormalTok{ df)}
\NormalTok{anova\_summary }\OtherTok{\textless{}{-}} \FunctionTok{summary}\NormalTok{(anova\_results)}
\NormalTok{anova\_summary}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##                     Df Sum Sq Mean Sq F value   Pr(>F)    
## Type                 1   3366    3366 399.758  < 2e-16 ***
## Treatment            1    988     988 117.368 2.32e-15 ***
## conc                 6   4069     678  80.548  < 2e-16 ***
## Type:Treatment       1    226     226  26.812 3.15e-06 ***
## Type:conc            6    374      62   7.412 7.24e-06 ***
## Treatment:conc       6    101      17   1.999   0.0811 .  
## Type:Treatment:conc  6    112      19   2.216   0.0547 .  
## Residuals           56    471       8                     
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
\end{verbatim}

\subsubsection{7.1 Analyse des résultats de l'ANOVA à trois
facteurs}\label{analyse-des-ruxe9sultats-de-lanova-uxe0-trois-facteurs}

Le tableau ANOVA révèle des effets hautement significatifs des trois
facteurs principaux sur la fixation de CO₂. L'origine géographique
(Type) présente l'effet le plus marqué (F(1,56) = 399.76, p \textless{}
0.0001), expliquant à lui seul une part importante de la variance
totale. Le traitement thermique (Treatment) montre également un impact
très significatif (F(1,56) = 117.37, p = 2.32e-15), tandis que la
concentration en \(CO_2\) (conc) démontre une relation dose-réponse non
linéaire particulièrement robuste (F(6,56) = 80.55, p \textless{}
0.0001). Ces résultats confirment nos hypothèses initiales quant à
l'influence déterminante de ces paramètres environnementaux sur
l'activité photosynthétique.

L'analyse des interactions révèle des dynamiques complexes entre les
facteurs. L'interaction double Type:Treatment (F(1,56) = 26.81, p =
3.15e-06) indique que l'effet du stress thermique varie
significativement selon l'origine géographique des plantes. De même,
l'interaction Type:conc (F(6,56) = 7.41, p = 7.24e-06) suggère que la
réponse aux différentes concentrations de \(CO_2\) est modulée par le
génotype des plantes. Les interactions Treatment:conc (p = 0.081) et
triple Type:Treatment:conc (p = 0.055) approchent le seuil de
significativité, révélant des tendances qui mériteraient des
investigations complémentaires avec un échantillon plus large.

D'un point de vue méthodologique, ces résultats valident pleinement
notre approche multifactorielle. La proportion de variance expliquée par
le modèle (R² ajusté élevé) et la cohérence des effets détectés avec les
connaissances physiologiques végétales renforcent la crédibilité de nos
conclusions. Les effets résiduels relativement faibles suggèrent que
notre modèle capture l'essentiel des sources de variation. Ces analyses
ouvrent des perspectives intéressantes pour comprendre les mécanismes
d'adaptation des plantes face aux changements climatiques,
particulièrement concernant les interactions entre température et
concentration en \(CO_2\).

\subsubsection{7.2 Analyse post-hoc des
différences}\label{analyse-post-hoc-des-diffuxe9rences}

\paragraph{Effet Treatment}\label{effet-treatment}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{em\_trt }\OtherTok{\textless{}{-}} \FunctionTok{emmeans}\NormalTok{(model, pairwise }\SpecialCharTok{\textasciitilde{}}\NormalTok{ Treatment, }\AttributeTok{adjust =} \StringTok{"tukey"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## NOTE: Results may be misleading due to involvement in interactions
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{em\_trt}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## $emmeans
##  Treatment  emmean    SE df lower.CL upper.CL
##  nonchilled   30.6 0.448 56     29.7     31.5
##  chilled      23.8 0.448 56     22.9     24.7
## 
## Results are averaged over the levels of: Type, conc 
## Confidence level used: 0.95 
## 
## $contrasts
##  contrast             estimate    SE df t.ratio p.value
##  nonchilled - chilled     6.86 0.633 56  10.834  <.0001
## 
## Results are averaged over the levels of: Type, conc
\end{verbatim}

Les comparaisons multiples ajustées par la méthode de Tukey révèlent un
écart moyen hautement significatif (p \textless{} 0,0001) de 6,86
μmol/m²s entre les plantes nonchilled (moyenne = 30,6) et chilled
(moyenne = 23,8). Cet écart considérable, représentant une réduction
relative de 22,4\% sous stress thermique, confirme l'impact majeur du
traitement sur l'activité photosynthétique. Les intervalles de confiance
à 95\% (nonchilled : {[}29,7-31,5{]} ; chilled : {[}22,9-24,7{]}) ne se
chevauchent pas, renforçant la robustesse de ce résultat.

L'analyse met cependant en garde contre une interprétation isolée de ces
effets, soulignant que les différences observées sont moyennées sur tous
les niveaux des autres facteurs (Type et concentration). Cette réserve
méthodologique est cruciale : elle implique que l'ampleur réelle de
l'effet thermique pourrait varier selon l'origine géographique des
plantes ou la concentration en \(CO_2\), comme le suggéraient d'ailleurs
les interactions significatives détectées dans l'ANOVA.

\paragraph{Interaction Type x
Treatment}\label{interaction-type-x-treatment}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{em\_type\_trt }\OtherTok{\textless{}{-}} \FunctionTok{emmeans}\NormalTok{(model, pairwise }\SpecialCharTok{\textasciitilde{}}\NormalTok{ Type }\SpecialCharTok{|}\NormalTok{ Treatment, }\AttributeTok{adjust =} \StringTok{"tukey"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## NOTE: Results may be misleading due to involvement in interactions
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{em\_type\_trt}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## $emmeans
## Treatment = nonchilled:
##  Type        emmean    SE df lower.CL upper.CL
##  Quebec        35.3 0.633 56     34.1     36.6
##  Mississippi   26.0 0.633 56     24.7     27.2
## 
## Treatment = chilled:
##  Type        emmean    SE df lower.CL upper.CL
##  Quebec        31.8 0.633 56     30.5     33.0
##  Mississippi   15.8 0.633 56     14.5     17.1
## 
## Results are averaged over the levels of: conc 
## Confidence level used: 0.95 
## 
## $contrasts
## Treatment = nonchilled:
##  contrast             estimate    SE df t.ratio p.value
##  Quebec - Mississippi     9.38 0.895 56  10.476  <.0001
## 
## Treatment = chilled:
##  contrast             estimate    SE df t.ratio p.value
##  Quebec - Mississippi    15.94 0.895 56  17.799  <.0001
## 
## Results are averaged over the levels of: conc
\end{verbatim}

L'analyse des moyennes marginales estimées met en évidence une
\textbf{interaction significative entre les facteurs \texttt{Treatment}
(refroidissement) et \texttt{Type} (origine des plantes)}. Cette
interaction signifie que l'effet du traitement sur la fixation de CO₂
varie selon le type de plante, et inversement.

Plus précisément :

\begin{itemize}
\item
  En l'absence de refroidissement (\texttt{nonchilled}), les plantes
  originaires du \textbf{Quebec} présentent une fixation moyenne de CO₂
  de \textbf{35.3 µmol/m²·s}, contre \textbf{26.0 µmol/m²·s} pour celles
  du \textbf{Mississippi}. L'écart est de \textbf{+9.38 unités} en
  faveur du Quebec, avec une \textbf{significativité statistique très
  forte (p \textless{} 0.0001)}.
\item
  Sous condition de refroidissement (\texttt{chilled}), la fixation
  moyenne diminue pour les deux types, mais l'effet est \textbf{plus
  marqué pour les plantes du Mississippi} : \textbf{31.8 µmol/m²·s} pour
  le Quebec contre seulement \textbf{15.8 µmol/m²·s} pour le
  Mississippi. La différence atteint alors \textbf{+15.94 unités},
  toujours avec une \textbf{significativité très élevée (p \textless{}
  0.0001)}.
\end{itemize}

Cette évolution des écarts montre que le \textbf{refroidissement affecte
de façon différentielle les deux types de plantes}. Alors que les
plantes du Quebec conservent une bonne capacité de fixation sous froid,
celles du Mississippi subissent une réduction bien plus importante.

\paragraph{Interaction Type x conc}\label{interaction-type-x-conc}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{em\_type\_trc }\OtherTok{\textless{}{-}} \FunctionTok{emmeans}\NormalTok{(model, pairwise }\SpecialCharTok{\textasciitilde{}}\NormalTok{ Type }\SpecialCharTok{|}\NormalTok{ conc, }\AttributeTok{adjust =} \StringTok{"tukey"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## NOTE: Results may be misleading due to involvement in interactions
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{em\_type\_trc}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## $emmeans
## conc = 95:
##  Type        emmean   SE df lower.CL upper.CL
##  Quebec        14.1 1.18 56    11.69     16.4
##  Mississippi   10.4 1.18 56     8.08     12.8
## 
## conc = 175:
##  Type        emmean   SE df lower.CL upper.CL
##  Quebec        27.1 1.18 56    24.71     29.5
##  Mississippi   17.5 1.18 56    15.11     19.9
## 
## conc = 250:
##  Type        emmean   SE df lower.CL upper.CL
##  Quebec        35.9 1.18 56    33.56     38.3
##  Mississippi   21.8 1.18 56    19.44     24.2
## 
## conc = 350:
##  Type        emmean   SE df lower.CL upper.CL
##  Quebec        38.1 1.18 56    35.71     40.5
##  Mississippi   23.2 1.18 56    20.88     25.6
## 
## conc = 500:
##  Type        emmean   SE df lower.CL upper.CL
##  Quebec        38.1 1.18 56    35.76     40.5
##  Mississippi   23.6 1.18 56    21.24     26.0
## 
## conc = 675:
##  Type        emmean   SE df lower.CL upper.CL
##  Quebec        39.5 1.18 56    37.13     41.9
##  Mississippi   24.4 1.18 56    22.03     26.8
## 
## conc = 1000:
##  Type        emmean   SE df lower.CL upper.CL
##  Quebec        42.0 1.18 56    39.63     44.4
##  Mississippi   25.2 1.18 56    22.79     27.5
## 
## Results are averaged over the levels of: Treatment 
## Confidence level used: 0.95 
## 
## $contrasts
## conc = 95:
##  contrast             estimate   SE df t.ratio p.value
##  Quebec - Mississippi     3.62 1.68 56   2.159  0.0352
## 
## conc = 175:
##  contrast             estimate   SE df t.ratio p.value
##  Quebec - Mississippi     9.60 1.68 56   5.731  <.0001
## 
## conc = 250:
##  contrast             estimate   SE df t.ratio p.value
##  Quebec - Mississippi    14.12 1.68 56   8.427  <.0001
## 
## conc = 350:
##  contrast             estimate   SE df t.ratio p.value
##  Quebec - Mississippi    14.83 1.68 56   8.855  <.0001
## 
## conc = 500:
##  contrast             estimate   SE df t.ratio p.value
##  Quebec - Mississippi    14.52 1.68 56   8.666  <.0001
## 
## conc = 675:
##  contrast             estimate   SE df t.ratio p.value
##  Quebec - Mississippi    15.10 1.68 56   9.014  <.0001
## 
## conc = 1000:
##  contrast             estimate   SE df t.ratio p.value
##  Quebec - Mississippi    16.83 1.68 56  10.049  <.0001
## 
## Results are averaged over the levels of: Treatment
\end{verbatim}

Les résultats des \textbf{moyennes marginales estimées} et des
\textbf{contrastes} montrent une \textbf{interaction significative entre
le type de plante (\texttt{Type}) et la concentration de CO₂
(\texttt{conc})}. L'effet du type varie selon le niveau de
concentration, ce qui empêche une interprétation globale de l'effet
principal de \texttt{Type}.

\textbf{Résultats par concentration}

\begin{itemize}
\item
  À \textbf{faible concentration (95)} :

  \begin{itemize}
  \tightlist
  \item
    Québec : 14.1
  \item
    Mississippi : 10.4
  \item
    Différence : \textbf{3.62} (p = 0.0352)
  \end{itemize}

  L'écart est faible mais significatif, en faveur du Québec.
\item
  À partir de \textbf{175 jusqu'à 1000}, l'écart devient de plus en plus
  important :

  \begin{itemize}
  \tightlist
  \item
    À 250 : \textbf{+14.12} (p \textless{} 0.0001)
  \item
    À 500 : \textbf{+14.52} (p \textless{} 0.0001)
  \item
    À 1000 : \textbf{+16.83} (p \textless{} 0.0001)
  \end{itemize}
\end{itemize}

\textbf{Interprétation}

L'\textbf{écart de performance entre les plantes du Québec et du
Mississippi augmente avec la concentration de CO₂}. Cela indique que les
plantes québécoises répondent plus favorablement à l'augmentation de CO₂
que celles du Mississippi.

L'effet du type de plante n'est donc \textbf{pas constant} selon les
niveaux de concentration, ce qui \textbf{confirme l'existence d'une
interaction significative}. En présence de cette interaction, les
comparaisons doivent être \textbf{conditionnelles au niveau de
concentration}, comme illustré par les contrastes spécifiques à chaque
\texttt{conc}.

Cette interaction implique que l'effet du type ne peut être résumé par
une seule différence moyenne, car il dépend du contexte de
concentration.

\paragraph{Graphique des moyennes
marginales}\label{graphique-des-moyennes-marginales}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{emmip}\NormalTok{(model, Treatment }\SpecialCharTok{\textasciitilde{}}\NormalTok{ conc }\SpecialCharTok{|}\NormalTok{ Type, }\AttributeTok{CIs =} \ConstantTok{TRUE}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{theme\_minimal}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}
    \AttributeTok{title =} \StringTok{"Moyennes marginales estimées"}\NormalTok{, }
    \AttributeTok{y =} \StringTok{"Fixation de CO2 prédite (umol/m\^{}2.s)"}\NormalTok{,  }
    \AttributeTok{x =} \StringTok{"Concentration CO2 (mL/L)"}
\NormalTok{  ) }\SpecialCharTok{+}
  \FunctionTok{theme}\NormalTok{(}\AttributeTok{axis.text.x =} \FunctionTok{element\_text}\NormalTok{(}\AttributeTok{angle =} \DecValTok{45}\NormalTok{, }\AttributeTok{hjust =} \DecValTok{1}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{center}\includegraphics{Corrected_ANOVA_Trois_Facteurs_files/figure-latex/unnamed-chunk-17-1} \end{center}

\textbf{Description}

Le graphique montre les moyennes marginales estimées de la fixation de
\(CO_2\) (en µmol/m²/s) en fonction de la concentration de \(CO_2\) (en
mL/L) pour deux régions : Québec et Mississippi. Deux traitements sont
comparés : ``nonchilled'' (non refroidi, en rouge) et ``chilled''
(refroidi, en cyan). Les données incluent des lignes de tendance avec
des barres d'erreur à chaque concentration (95, 175, 250, 330, 500, 675,
1000 mL/L). Québec : La fixation augmente avec la concentration de
\(CO_2\), avec ``nonchilled'' surpassant ``chilled'', surtout à partir
de 330 mL/L. Mississippi : La fixation augmente également, mais reste
plus basse que Québec, avec un écart moindre entre ``nonchilled'' et
``chilled''.

\textbf{Interprétation}

Concentration de \(CO_2\) : L'augmentation de la fixation avec la
concentration de CO₂ reflète une réponse typique de la photosynthèse, où
plus de \(CO_2\) disponible améliore l'activité photosynthétique.

Traitement : Le ``nonchilled'' favorise une fixation plus élevée,
suggérant que des températures plus hautes optimisent les enzymes
photosynthétiques, tandis que le ``chilled'' semble limiter cette
activité.

Régions : Québec montre une fixation supérieure à Mississippi,
possiblement due à des adaptations génétiques ou climatiques (Québec
plus froid, Mississippi plus chaud), ou à des différences locales
(lumière, humidité).

Le traitement ``nonchilled'' est plus efficace pour la fixation de
\(CO_2\) dans les deux régions, avec une performance notablement
meilleure au Québec. Ces résultats indiquent que des températures plus
élevées favorisent la photosynthèse et que les plantes du Québec
pourraient être mieux adaptées à exploiter le \(CO_2\). Cela pourrait
guider la sélection de variétés végétales ou les stratégies agricoles
face aux variations climatiques ou à l'enrichissement en \(CO_2\).

\section{Conclusion}\label{conclusion}

Cette étude approfondie des déterminants de la fixation du CO₂ chez les
plantes nous a révélé une architecture complexe d'effets principaux et
d'interactions. L'analyse ANOVA trois facteurs a révélé des effets
majeurs significatifs des trois facteurs étudiés sur la fixation du CO₂.
L'origine géographique s'est avérée le facteur le plus discriminant, les
plantes québécoises présentant une efficacité photosynthétique
supérieure, reflétant leur adaptation aux climats froids. Le traitement
thermique a montré un impact tout aussi marqué, avec une réduction
moyenne de 22.4\% sous stress froid, confirmant la sensibilité
universelle de l'appareil photosynthétique aux basses températures.
Parallèlement, la concentration en CO₂ a dévoilé une relation
dose-réponse complexe, caractérisée par une phase de stimulation
linéaire suivie d'un plateau de saturation aux hautes concentrations.

\section{Références}\label{ruxe9fuxe9rences}

\begin{itemize}
\tightlist
\item
  Maxwell, S. E., \& Delaney, H. D. (2004). \emph{Designing Experiments
  and Analyzing Data: A Model Comparison Perspective}.
\item
  Lenth, R. V. (2021). \emph{emmeans: Estimated Marginal Means, aka
  Least-Squares Means} (R package).
\item
  \url{https://perso.univ-rennes1.fr/valerie.monbet/ExposesM2/2013/anova.pdf}\strut \\
\item
  \url{https://miashs-www.u-ga.fr/prevert/MathSHS/PSY3/ANOVA/Cours/ANOVA.pdf}
\end{itemize}

\end{document}
